blank_issues_enabled: true
contact_links:
  - name: Ask a question ‚ùì
    url: https://github.com/leefrost/httpclient.cache/discussions/new
    about: Ask a question or request support for using the template